services:
  index-tts:
    image: ${IMAGE:-crpi-1ox9stng93ipbprt.cn-beijing.personal.cr.aliyuncs.com/wang666233/wang666233:latest}
    pull_policy: if_not_present
    environment:
      - DOWNLOAD_MODEL=${DOWNLOAD_MODEL:-2}
      - CONVERT_MODEL=${CONVERT_MODEL:-2}
      - MODEL_DIR=${MODEL_DIR:-/app/checkpoints/IndexTTS-2-vLLM}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8001}
      - IS_FP16=${IS_FP16:-1}
      - ENABLE_QWEN_EMO=${ENABLE_QWEN_EMO:-1}
      - DISABLE_QWEN_EMO=${DISABLE_QWEN_EMO:-0}
      - VERBOSE=${VERBOSE:-0}
      - GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.25}
      - QWENEMO_GPU_MEMORY_UTILIZATION=${QWENEMO_GPU_MEMORY_UTILIZATION:-0.10}
    container_name: index-tts-server
    ports:
      - "${HOST_PORT:-6006}:${PORT:-8001}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
    #   - ./audio_prompts:/app/audio_prompts
      - ./assets:/app/assets
      - ${CHECKPOINTS_DIR:-./checkpoints}:/app/checkpoints:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8001}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
